# https://taskfile.dev

version: '3'

env:
  latest_go:
    sh: curl -s https://go.dev/VERSION\?m\=text | head -n1 | sed 's/^go//'
  latest_pagefind:
    sh: gh release list -L 1 -R CloudCannon/pagefind --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName' | sed 's/^v//'
  latest_hugo:
    sh: gh release list -L 1 -R gohugoio/hugo --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName' | sed 's/^v//'
  latest_task:
    sh: gh release list -L 1 -R go-task/task --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName' | sed 's/^v//'
  latest_lychee:
    sh: gh release list -L 1 -R lycheeverse/lychee --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName' | sed 's/^v//'


tasks:
  upgrade:
    cmds:
      - gsed -i 's/FROM golang:.*-/FROM golang:{{ .latest_go }}-/' Dockerfile
      - gsed -i 's/PAGEFIND_VERSION=.*$/PAGEFIND_VERSION={{ .latest_pagefind }}/' Dockerfile
      - gsed -i 's/TASK_VERSION=.*$/TASK_VERSION={{ .latest_task }}/' Dockerfile
      - gsed -i 's/LYCHEE_VERSION=.*$/LYCHEE_VERSION={{ .latest_lychee }}/' Dockerfile
      - gsed -i 's/HUGO_VERSION=.*$/HUGO_VERSION={{ .latest_hugo }}/' Dockerfile
